import {getVersion} from "./helpers/getVersion";

export const potHeader = `# Generated by Freave POT generator ${getVersion()}\n` +
    '#\n' +
    '#, fuzzy\n' +
    'msgid ""\n' +
    'msgstr ""\n' +
    '"Project-Id-Version: freaveflex \\n"\n' +
    '"Report-Msgid-Bugs-To: Freave \\n"\n' +
    '"Last-Translator: Freave \\n"\n' +
    '"Language-Team: Freave \\n"\n' +
    '"MIME-Version: 1.0 \\n"\n' +
    '"Content-Type: text/plain; charset=UTF-8 \\n"\n' +
    '"Content-Transfer-Encoding: 8bit \\n"\n' +
    '"POT-Creation-Date: ' + new Date().toISOString() + ' \\n"\n' +
    '"PO-Revision-Date: ' + new Date().toISOString() + ' \\n"\n' +
    '"X-Generator:  Freave POT generator ' + getVersion() + ' \\n"\n';
