import {getVersion} from "./helpers/getVersion";

export const potHeader = `# Generated by Freave create-pot ${getVersion()}\n` +
    '#\n' +
    '#, fuzzy\n' +
    'msgid ""\n' +
    'msgstr ""\n' +
    '"Project-Id-Version: freaveflex \\n"\n' +
    '"Report-Msgid-Bugs-To: Freave \\n"\n' +
    '"Last-Translator: Freave \\n"\n' +
    '"Language-Team: Freave \\n"\n' +
    '"MIME-Version: 1.0 \\n"\n' +
    '"Content-Type: text/plain; charset=UTF-8 \\n"\n' +
    '"Content-Transfer-Encoding: 8bit \\n"\n' +
    '"POT-Creation-Date: ' + new Date().toISOString() + ' \\n"\n' +
    '"PO-Revision-Date: ' + new Date().toISOString() + ' \\n"\n' +
    '"X-Generator:  Freave create-pot ' + getVersion() + ' \\n"\n';

interface MatchGroup {
    /** Name of the WordPress translation function */
    wpFunction: string;
    /** The Regex for finding matches */
    matchRegex: RegExp;
    /** The Regex for extracting the parameters */
    extractRegex: RegExp;
    /** Function for formatting a single matchRegex result. */
    formatMatch: (match: string[]) => any;
}

export const matchGroups: MatchGroup[] = [
    {
        wpFunction: '_x',
        matchRegex: new RegExp(/(?<!esc_attr|esc_html)_x\(.*?\)/gs),
        extractRegex: new RegExp(/_x\(\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*\)/),
        formatMatch: (match: string[]) => {
            return {
                text: match[1],
                context: match[2],
                domain: match[3]
            };
        }
    },
    {
        wpFunction: '__',
        matchRegex: new RegExp(/(?<!esc_attr|esc_html)__\(.*?\)/gs),
        extractRegex: new RegExp(/__\(\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*\)/),
        formatMatch: (match: string[]) => {
            return {
                text: match[1],
                domain: match[2]
            };
        }
    },
    {
        wpFunction: '_e',
        matchRegex: new RegExp(/(?<!esc_attr|esc_html)_e\(.*?\)/gs),
        extractRegex: new RegExp(/_e\(\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*\)/),
        formatMatch: (match: string[]) => {
            return {
                text: match[1],
                domain: match[2]
            };
        }
    },
    {
        wpFunction: 'esc_attr__',
        matchRegex: new RegExp(/esc_attr__\(.*?\)/gs),
        extractRegex: new RegExp(/esc_attr__\(\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*\)/),
        formatMatch: (match: string[]) => {
            return {
                text: match[1],
                domain: match[2]
            };
        }
    },
    {
        wpFunction: 'esc_attr_e',
        matchRegex: new RegExp(/esc_attr_e\(.*?\)/gs),
        extractRegex: new RegExp(/esc_attr_e\(\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*\)/),
        formatMatch: (match: string[]) => {
            return {
                text: match[1],
                domain: match[2]
            };
        }
    },
    {
        wpFunction: 'esc_html__',
        matchRegex: new RegExp(/esc_html__\(.*?\)/gs),
        extractRegex: new RegExp(/esc_html__\(\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*\)/),
        formatMatch: (match: string[]) => {
            return {
                text: match[1],
                domain: match[2]
            };
        }
    },
    {
        wpFunction: 'esc_html_e',
        matchRegex: new RegExp(/esc_html_e\(.*?\)/gs),
        extractRegex: new RegExp(/esc_html_e\(\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*\)/),
        formatMatch: (match: string[]) => {
            return {
                text: match[1],
                domain: match[2]
            };
        }
    },
    {
        wpFunction: '_ex',
        matchRegex: new RegExp(/_ex\(.*?\)/gs),
        extractRegex: new RegExp(/_ex\(\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*\)/),
        formatMatch: (match: string[]) => {
            return {
                text: match[1],
                context: match[2],
                domain: match[3]
            };
        }
    },
    {
        wpFunction: 'esc_attr_x',
        matchRegex: new RegExp(/esc_attr_x\(.*?\)/gs),
        extractRegex: new RegExp(/esc_attr_x\(\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*\)/),
        formatMatch: (match: string[]) => {
            return {
                text: match[1],
                context: match[2],
                domain: match[3]
            };
        }
    },
    {
        wpFunction: 'esc_html_x',
        matchRegex: new RegExp(/esc_html_x\(.*?\)/gs),
        extractRegex: new RegExp(/esc_html_x\(\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*,\s*['"](.*?)['"]\s*\)/),
        formatMatch: (match: string[]) => {
            return {
                text: match[1],
                context: match[2],
                domain: match[3]
            };
        }
    },
]
